// This file is generated by Sapper — do not edit it!
export const timestamp = 1541808852920;

export const files = [
	"500-128.png",
	"500-256.png",
	"500-512.png",
	"favicon.png",
	"global.css",
	"manifest.json",
	"planet-earth.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/chunk.18badf4c.js",
	"client/client.fe2fc68f.js",
	"client/index.85599372.js",
	"client/bar.8de5b496.js",
	"client/foo.5ba113ab.js",
	"client/sapper-dev-client.c1ed07a9.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/bar\/?$/ },
	{ pattern: /^\/foo\/?$/ }
];