// This file is generated by Sapper — do not edit it!
export const timestamp = 1541844925456;

export const files = [
	"500-128.png",
	"500-256.png",
	"500-512.png",
	"500_app_icon_192x192px.png",
	"500_app_icon_512x512px.png",
	"favicon.png",
	"global.css",
	"img/1onboarding1.png",
	"img/2onboarding2.png",
	"img/3Onboarding3.png",
	"img/adventure.jpg",
	"img/coop.png",
	"img/kottataren22.png",
	"img/lillamy.png",
	"img/line2.png",
	"img/line3.png",
	"img/map.png",
	"img/planet.png",
	"img/simonfredrikk.png",
	"img/tova_strid.png",
	"manifest.json",
	"planet-earth.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/chunk.11ef0f39.js",
	"client/client.7ae6bb5b.js",
	"client/chunk.1c55ad38.js",
	"client/chunk.8678b8c9.js",
	"client/index.6cf524e4.js",
	"client/tillsammans.47aee534.js",
	"client/registrera.436e0771.js",
	"client/anvandare.16b4408f.js",
	"client/framsteg.8affe16a.js",
	"client/search.3b2630e9.js",
	"client/intro.af1528a8.js",
	"client/sapper-dev-client.c1ed07a9.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/tillsammans\/?$/ },
	{ pattern: /^\/registrera\/?$/ },
	{ pattern: /^\/anvandare\/?$/ },
	{ pattern: /^\/framsteg\/?$/ },
	{ pattern: /^\/search\/?$/ },
	{ pattern: /^\/intro\/?$/ }
];