// This file is generated by Sapper — do not edit it!
export const timestamp = 1541848101654;

export const files = [
	"500-128.png",
	"500-256.png",
	"500-512.png",
	"500_app_icon_192x192px.png",
	"500_app_icon_512x512px.png",
	"favicon.png",
	"global.css",
	"img/1onboarding1.png",
	"img/2onboarding2.png",
	"img/3Onboarding3.png",
	"img/adventure.jpg",
	"img/coop.png",
	"img/gnesta-turtles.png",
	"img/gubbar-som-cyklar.png",
	"img/kottataren22.png",
	"img/lillamy.png",
	"img/line2.png",
	"img/line3.png",
	"img/map.png",
	"img/map2.png",
	"img/na17a.png",
	"img/planet.png",
	"img/simonfredrikk.png",
	"img/tova_strid.png",
	"manifest.json",
	"planet-earth.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/chunk.9e933716.js",
	"client/client.823e1cf8.js",
	"client/chunk.87b5a8c5.js",
	"client/chunk.8678b8c9.js",
	"client/index.0a5ffea7.js",
	"client/tillsammans.7cc24a66.js",
	"client/registrera.a1c0b65d.js",
	"client/anvandare.c911f31c.js",
	"client/framsteg.0c7cb6b2.js",
	"client/search.feeff4d7.js",
	"client/intro.ec304db2.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/tillsammans\/?$/ },
	{ pattern: /^\/registrera\/?$/ },
	{ pattern: /^\/anvandare\/?$/ },
	{ pattern: /^\/framsteg\/?$/ },
	{ pattern: /^\/search\/?$/ },
	{ pattern: /^\/intro\/?$/ }
];