(function () {
	'use strict';

	// This file is generated by Sapper — do not edit it!
	const timestamp = 1541848101654;

	const files = [
		"500-128.png",
		"500-256.png",
		"500-512.png",
		"500_app_icon_192x192px.png",
		"500_app_icon_512x512px.png",
		"favicon.png",
		"global.css",
		"img/1onboarding1.png",
		"img/2onboarding2.png",
		"img/3Onboarding3.png",
		"img/adventure.jpg",
		"img/coop.png",
		"img/gnesta-turtles.png",
		"img/gubbar-som-cyklar.png",
		"img/kottataren22.png",
		"img/lillamy.png",
		"img/line2.png",
		"img/line3.png",
		"img/map.png",
		"img/map2.png",
		"img/na17a.png",
		"img/planet.png",
		"img/simonfredrikk.png",
		"img/tova_strid.png",
		"manifest.json",
		"planet-earth.png"
	];

	const shell = [
		"client/chunk.9e933716.js",
		"client/client.823e1cf8.js",
		"client/chunk.87b5a8c5.js",
		"client/chunk.8678b8c9.js",
		"client/index.0a5ffea7.js",
		"client/tillsammans.7cc24a66.js",
		"client/registrera.a1c0b65d.js",
		"client/anvandare.c911f31c.js",
		"client/framsteg.0c7cb6b2.js",
		"client/search.feeff4d7.js",
		"client/intro.ec304db2.js"
	];

	const ASSETS = `cache${timestamp}`;

	// `shell` is an array of all the files generated by Rollup,
	// `files` is an array of everything in the `static` directory
	const to_cache = shell.concat(files);
	const cached = new Set(to_cache);

	self.addEventListener('install', event => {
		event.waitUntil(
			caches
				.open(ASSETS)
				.then(cache => cache.addAll(to_cache))
				.then(() => {
					self.skipWaiting();
				})
		);
	});

	self.addEventListener('activate', event => {
		event.waitUntil(
			caches.keys().then(async keys => {
				// delete old caches
				for (const key of keys) {
					if (key !== ASSETS) await caches.delete(key);
				}

				self.clients.claim();
			})
		);
	});

	self.addEventListener('fetch', event => {
		if (event.request.method !== 'GET' || event.request.headers.has('range')) return;

		const url = new URL(event.request.url);

		// don't try to handle e.g. data: URIs
		if (!url.protocol.startsWith('http')) return;

		// ignore dev server requests
		if (url.hostname === self.location.hostname && url.port !== self.location.port) return;

		// always serve static files and Rollup-generated assets from cache
		if (url.host === self.location.host && cached.has(url.pathname)) {
			event.respondWith(caches.match(event.request));
			return;
		}

		// for pages, you might want to serve a shell `index.html` file,
		// which Sapper has generated for you. It's not right for every
		// app, but if it's right for yours then uncomment this section
		/*
		if (url.origin === self.origin && routes.find(route => route.pattern.test(url.pathname))) {
			event.respondWith(caches.match('/index.html'));
			return;
		}
		*/

		if (event.request.cache === 'only-if-cached') return;

		// for everything else, try the network first, falling back to
		// cache if the user is offline. (If the pages never change, you
		// might prefer a cache-first approach to a network-first one.)
		event.respondWith(
			caches
				.open(`offline${timestamp}`)
				.then(async cache => {
					try {
						const response = await fetch(event.request);
						cache.put(event.request, response.clone());
						return response;
					} catch(err) {
						const response = await cache.match(event.request);
						if (response) return response;

						throw err;
					}
				})
		);
	});

}());
